# This blank workflow is placeholder for a build
name: Build application example

on:
  workflow_call:

jobs:
  build-application:
    runs-on: ubuntu-latest
    steps:
      - name: Mock Build App Step
        run: echo "This is where the app would build"
