# This example shows a Manual callable workflow through the Github UI
name: Build Caller (dispatcher)

on: workflow_dispatch

jobs:
  run-build:
    uses: ./.github/workflows/build.yaml
    secrets: inherit
    with:
      SOME_INPUT: "Test Var Passing Data"
