name: Build application example

on:
  workflow_call:
    inputs:
      SOME_INPUT:
        required: true
        type: string

jobs:
  build-application:
    runs-on: ubuntu-latest
    steps:
      - name: Mock Build App Step
        run: echo "This is where the app would build"
