name: Creates a PR to the Development Branch

on: workflow_call

jobs:
  create-pr:
    name: "Create PR to back merge to development"
    uses: "actions/github-script@v6"
    with:
      github-token: "${{ secrets.GITHUB_TOKEN }}"
      script: |
        try {
          await github.rest.pulls.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: "Merge main back into development",
            body: "Created using Github Actions after release [${{steps.date.outputs.date}}](/ua-digital-commerce/ua-commerce-api/releases/tag/${{steps.date.outputs.date}})",
            head: "main",
            base: "development",
          });
        } catch (error) {
          core.setFailed(error.message);
        }
