# This example shows a Manual callable workflow through the Github UI
name: Manually Run Tests (dispatcher)

on: workflow_dispatch

jobs:
  run-build:
    uses: ./.github/workflows/run-tests.yaml
    secrets: inherit
