name: Development/Main PR Dispatcher
# This dispatcher triggers on pull request of Main/Development branch
on:
  pull_request:
    branches:
      - development
      - main

  # checking to see if this is the magic
  schedule:
    - cron: "41 3 * * 2"

jobs:
  run-tests:
    uses: ./.github/workflows/run-tests.yaml
    secrets: inherit
