name: Development/Main PR Dispatcher
# This dispatcher triggers on pull request of Main/Development branch
on:
  pull_request:
    branches:
      - development
      - main

  # checking to see if this is the magic
  #   ┌───────────── minute (0 - 59)
  # │ ┌───────────── hour (0 - 23)
  # │ │ ┌───────────── day of the month (1 - 31)
  # │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
  # │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
  # │ │ │ │ │
  # │ │ │ │ │
  # │ │ │ │ │
  # * * * * *
  schedule:
    - cron: "41 9 * * *"

jobs:
  run-tests:
    uses: ./.github/workflows/run-tests.yaml
    secrets: inherit
