name: Push Main Dispatcher
# This dispatcher triggers on push of Main branch
on:
  push:
    branches:
      - main

jobs:
  create-pr-to-dev:
    uses: ./.github/workflows/create-pr-development.yaml
    secrets: inherit

  run-tests:
    needs:
      - create-pr-to-dev
    uses: antho1jp/github-workflows-devops/.github/workflows/run-tests.yaml@development
    secrets: inherit
