name: Push Main Dispatcher
# This dispatcher triggers on push of Main branch
on:
  push:
    branches:
      - main

jobs:
  create-pr-to-dev:
    uses: antho1jp/github-workflows-devops/.github/workflows/create-pr-development.yaml@development
    secrets: inherit
    with:
      SOME_INPUT: "Test Var Passing Data"
